apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-golang-example
  namespace: golang-example
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - api.golang-example.com
      secretName: golang-example-tls
  rules:
    - host: api.golang-example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: golang-example
                port:
                  number: 8080