apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: golang-example
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  # The project the application belongs to.
  project: default

  # Source of the application manifests
  source:
    repoURL: https://github.com/aikkul3iw/golang-example.git
    targetRevision: master
    path: gitops/golang-example

    # helm specific config
    helm:
      valueFiles:
      - values.yaml

  # Destination cluster and namespace to deploy the application
  destination:
    server: https://kubernetes.default.svc
    namespace: golang-example

  # Sync policy
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true # Specifies if partial app sync should be executed when resources are changed only in target Kubernetes cluster and no git change detected ( false by default ).
