name: Build Go

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.1
    - name: Login to Docker Hub
      uses: docker/login-action@v3.0.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build and Push docker image
      uses: docker/build-push-action@v5.1.0
      with:
        context: .
        file: ./docker/Dockerfile
        push: true
        build-args: VERSION=1.0.0
        tags: ${{ secrets.DOCKER_USERNAME }}/golang-example:1.0.0